.TH RCCE 3  "September 2010"  "RCCE MANPAGE" "RCCE Library"
.SH NAME

RCCE_shfree \- deallocates memory that was allocated with RCCE_shmalloc(). 

.SH SYNOPSIS
.B #include <rcce.h>
.sp

.BI "void RCCE_shfree(volatile char * " ptr );

.SH DESCRIPTION
.BR RCCE_shfree()
deallocates memory that was allocated with RCCE_shmalloc() at address ptr.
This 
is a collective routine that must be called jointly by all UEs

.TP
.B size
The number of bytes to allocate in memory.

.SH "RETURN VALUE"
None.

.SH ERRORS
Look in 
.BR rcce.h
for additional error codes.

.SH "SEE ALSO"
rcce.h(5)

.SH EXAMPLE
.PP
To be supplied.
