.TH RCCE 3  2010-06-27 "RCCE MANPAGE" "RCCE Library"
.SH NAME
RCCE_get \-  copies contents from src to target (GORY)

.SH SYNOPSIS
.B #include <rcce.h>
.sp
.BI "int RCCE_get(volatile char * " target ",volatile char * ",src ",int " num_bytes ",int " ID );

.SH DESCRIPTION
.BR RCCE_get()
copies the contents of the buffer pointed to by src into the location pointed to by target.  

.TP
.B
target
Address in calling UE.s local MPB or the private memory of the calling UE that \
points to the data to be gotten.
.TP
.B
src
An offset that, when combined with the ID, points to the source MPB. 
.TP
.B
num_bytes
Number of bytes to copy to the target.
.TP
.B
ID
Rank of the target UE.


.SH "RETURN VALUE"
Upon successful completion
.BR RCCE_get()
returns
.BR RCCE_SUCCESS .

.SH ERRORS
Look in 
.BR rcce.h
for additional error codes.

.SH "SEE ALSO"
rcce.h(5)

.SH EXAMPLE
.PP
To be supplied.
