.TH RCCE 3  2010-02-04 "RCCE MANPAGE" "RCCE Library"
.SH NAME
RCCE_num_ues \- returns the number of units of execution (n) participating in the computation.

.SH SYNOPSIS
.B #include <rcce.h>
.sp

.BI "int RCCE_num_ues(void);

.SH DESCRIPTION
.BR RCCE_num_ues() 
returns the number of units of execution (n) participating in the computation.

.SH "RETURN VALUE"
An integer equalto the number of units of execution (n) participating in the computation.

.SH ERRORS
Look in 
.BR rcce.h
for additional error codes.

.SH "SEE ALSO"
rcce.h(5)

.SH EXAMPLE
