.TH RCCE 3  2010-06-27 "RCCE MANPAGE" "RCCE Library"
.SH NAME
RCCE_flag_read \- reads the flag status of the UE with rank ID (GORY)

.SH SYNOPSIS
.B #include <rcce.h>
.sp
.BI "int RCCE_flag_read(RCCE_FLAG * " flag ",RCCE_FLAG_STATUS ",status ",int " ID );
.SH DESCRIPTION
.BR RCCE_flag_read()
reads the flag status of the UE with rank ID.

.TP
.B
flag
Pointer to a flag in MPB memory.
.TP
.B
status
An enumerated value (RCCE_FLAG_SET or RCCE_FLAG_UNSET) to be read in the flag location of the target UE. 
.TP
.B
ID
Rank of the target UE.

.SH "RETURN VALUE"
Upon successful completion
.BR RCCE_flag_read()
returns
.BR RCCE_SUCCESS .

.SH ERRORS
Look in 
.BR rcce.h
for additional error codes.

.SH "SEE ALSO"
rcce.h(5)

.SH EXAMPLE
.PP
To be supplied.
